### ISSUE TITLE
 Non-fatal Exception: java.lang.Exception   at _AnimationLimiterState.initState.<fn>(animation_limiter.dart:45)

### ISSUE THREAD

**Issue by kw2019ltd** [mobiten/flutter_staggered_animations#15] opened 2020-04-16 09:28 UTC
Non-fatal Exception: java.lang.Exception: NoSuchMethodError: The method 'markNeedsBuild' was called on null.
Receiver: null
Tried calling: markNeedsBuild()
       at State.setState(framework.dart:1168)
       at _AnimationLimiterState.initState.<fn>(animation_limiter.dart:45)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1102)
       at SchedulerBinding.handleDrawFrame(binding.dart:1049)
       at SchedulerBinding._handleDrawFrame(binding.dart:957)

![image](https://user-images.githubusercontent.com/47334522/79439595-b20e4100-7fdd-11ea-9b1a-2bb418410f93.png)

**Comment by MrLepage** [comment] 2021-03-01 18:49
Duplicate of #9 
Will be fixed in 0.1.3.

**Closed by MrLepage** 2021-03-01 18:49 UTC
