### ISSUE TITLE
Add option for curve

### ISSUE THREAD

**Issue by MuhammadDicky** [mobiten/flutter_staggered_animations#21] opened 2020-07-22 17:57 UTC
This great, I have same concept with this package on my app but in my app I can set curve on my own. So it will be great if another dev can set his own curve. And this type of animation is great on tab, on my project i  have function to trigger reverse animation when switch between tab, this also great if we can reverse the animation from this package.

**Comment by MrLepage** [comment] 2021-03-01 18:47
Duplicate of #22 
Curve param on animations will be released in 0.1.3.

**Closed by MrLepage** 2021-03-01 18:47 UTC
